{
	"identifiers": [
		"CVE-2018-20225"
	],
	"identifier": "CVE-2018-20225",
	"package_slug": "pypi/pip",
	"title": "False-Positive",
	"description": "This advisory has been marked as False-Positive and removed.",
	"date": "2024-08-26",
	"pubdate": "2020-05-08",
	"affected_range": "<0",
	"affected_versions": "None",
	"solution": "Unfortunately, there is no solution available yet.",
	"urls": [
		"https://nvd.nist.gov/vuln/detail/CVE-2018-20225",
		"https://pip.pypa.io/en/stable/news/"
	],
	"cwe_ids": [
		"CWE-1035",
		"CWE-20",
		"CWE-937"
	],
	"uuid": "f42440cc-317f-449c-87c3-016bee39ecbe",
	"cvss_v2": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
	"cvss_v3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
}
